version: '3.4'

services:
  master-db:
    container_name: master
    image: mysql:8.0
    volumes:
      - type: bind
        source: ./master/my.cnf
        target: /etc/mysql/conf.d/my.cnf
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=master
    networks:
      fixed_network:
        ipv4_address: 172.22.0.10

  slave-db:
    container_name: slave
    image: mysql:8.0
    volumes:
      - type: bind
        source: ./slave/my.cnf
        target: /etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=slave
    networks:
      fixed_network:
        ipv4_address: 172.22.0.20

  debug:
    image: adminer:latest
    ports:
      - 9000:8080
    networks:
      fixed_network:

networks:
  fixed_network:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24